version: "3"

volumes:
  letsencrypt:
    external: true

services:
  web-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt:/etc/letsencrypt:ro
      - ./nginx/proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: web-proxy
  
  gitlab:
    image: gitlab/gitlab-ce
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    container_name: gitlab
