concurrent = 1
check_interval = 0

[[runners]]
  name = "demo"
  url = "https://gitlab.linyc.idv.tw/"
  token = "322494168017e7460bdf17d095700b"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ubuntu:16.04"
    privileged = false
    disable_cache = false
    volumes = ["gitlab-runner-builds:/builds", "gitlab-runner-cache:/cache"]
    extra_hosts = ["gitlab.linyc.idv.tw:10.77.0.10"]
    network_mode = "docker-network"
    shm_size = 0
  [runners.cache]
